### ISSUE TITLE
«Cannot instantiate abstract class Df\Payment\Method in vendor/mage2pro/core/Payment/Method.php:1912»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [mage2pro/checkout.com#3]
Fatal error: Uncaught Error: Cannot instantiate abstract class Df\Payment\Method in vendor/mage2pro/core/Payment/Method.php:1912 
Stack trace: 
```
#0 vendor/mage2pro/core/Core/lib/cache.php(296): Df\Payment\Method::Df\Payment\{closure}('Df\\Payment\\Meth...') 
#1 vendor/mage2pro/core/Payment/Method.php(1912): dfcf(Object(Closure), Array) 
#2 vendor/mage2pro/core/Payment/lib/method.php(66): Df\Payment\Method::singleton(NULL) 
#3 vendor/mage2pro/core/Core/lib/cache.php(296): {closure}(Object(Magento\Sales\Model\Order\Interceptor)) 
#4 vendor/mage2pro/core/Payment/lib/method.php(73): dfcf(Object(Closure), Array) 
#5 vendor/mage2pro/core/Payment/lib/settings.php(36): dfpm(Object(Magento\Sales\Model\Order\Interceptor)) 
#6 vendor/mage2pro/checkout.com/Response.php(52): dfps(Object(Magento\Sales\Model\Order\Interceptor)) 
#7 vendor/mage2pro/checkout.com/Handler/C in vendor/mage2pro/core/Payment/Method.php on line 1912
```

**Comment by dmitrii-fediuk** [comment]
It is not a bug.  
It is happen when I make a 3D Secured payment on my localhost.
